//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationEmarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_product = new HashSet<tbl_product>();
        }
    
        public int U_id { get; set; }
        public string U_Name { get; set; }
        public string U_EMAIL { get; set; }
        public string U_password { get; set; }
        public string U_image { get; set; }
        public string U_Contact { get; set; }
    
        public virtual ICollection<tbl_product> tbl_product { get; set; }
    }
}
