//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationEmarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice12
    {
        public tbl_invoice12()
        {
            this.tbl_order12 = new HashSet<tbl_order12>();
        }
    
        public int in_id { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<double> in_totalbill { get; set; }
        public Nullable<int> in_fk_useer { get; set; }
    
        public virtual tbl_useer tbl_useer { get; set; }
        public virtual ICollection<tbl_order12> tbl_order12 { get; set; }
    }
}
