//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationEmarketing.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_useer
    {
        public tbl_useer()
        {
            this.tbl_invoice12 = new HashSet<tbl_invoice12>();
        }
    
        public int U1_id { get; set; }
        [Required(ErrorMessage="Name fill Reuired",AllowEmptyStrings=false)]
        public string U1_Name { get; set; }
        [Required (ErrorMessage="Contact fill Reuired",AllowEmptyStrings=false)]
        [StringLength(10,MinimumLength=10,ErrorMessage="please insert 1o digit")]
        public string U1_Contact { get; set; }
        [Required(ErrorMessage="Password Fill Required",AllowEmptyStrings=false)]
        [DataType(DataType.Password)]
        public string U1_paswword { get; set; }
    
        public virtual ICollection<tbl_invoice12> tbl_invoice12 { get; set; }
    }
}
