//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationEmarketing.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_purchase
    {
        public int id { get; set; }
       [Required(ErrorMessage="PLEASE ENTER THE NAME",AllowEmptyStrings=false)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Address1  is Required", AllowEmptyStrings = false)]
        public string Address1 { get; set; }
        [Required(ErrorMessage = "Address2   is Required", AllowEmptyStrings = false)]
        public string Address2 { get; set; }
        [Required(ErrorMessage = " Phone number is Required")]
        [StringLength(10, MinimumLength = 10,ErrorMessage="please insert 10 digit")] 
        public string phone { get; set; }
        [Required(ErrorMessage = " city  is Required")]
        public string city { get; set; }
        [Required(ErrorMessage = " country  is Required")]
        public string country { get; set; }
        [Required(ErrorMessage = " zipcode number is Required")]
        public string zIPCODE { get; set; }

    }
}
